version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
          name: Set up virtual environment and install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest  # just to be extra sure it's installed

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pytest -v tests/

workflows:
  version: 2
  test-deploy:
    jobs:
      - test